version: '3.8'

services:

  java-yasn:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: yasn
    depends_on:
      - mysql-db
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/yasn_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./src/main/resources/.env

  mysql-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: yasn_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - app-network
    env_file:
      - ./src/main/resources/.env

networks:
  app-network:
    driver: bridge
    name: yasn-network
