apiVersion: apps/v1
kind: Deployment
metadata:
  name: yasn
  namespace: yasn-app
  labels:
    app: yasn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yasn
  template:
    metadata:
      labels:
        app: yasn
    spec:
      containers:
        - name: yasn-container
          image: dvelichkov88/private-repo:yasn-1.0
          ports:
            - containerPort: 8000
              name: container-port
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yasn-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: yasn-secrets
                  key: CLOUDINARY_API_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yasn-secrets
                  key: DB_PASSWORD
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: yasn-service
  namespace: yasn-app
  labels:
    app: yasn
spec:
  ports:
    - port: 9800
      targetPort: 8000
      protocol: TCP
      name: container-port
  selector:
    app: yasn
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yasn-mysql
  namespace: yasn-app
  labels:
    app: yasn-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yasn-mysql
  template:
    metadata:
      labels:
        app: yasn-mysql
    spec:
      containers:
        - name: yasn-mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yasn-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: yasn-mysql-service
  namespace: yasn-app
  labels:
    app: yasn-mysql
spec:
  ports:
    - port: 9306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: yasn-mysql
  type: LoadBalancer
